---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 80, host: 80 }]
    - ["private_network", { ip: "192.168.33.33" }]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
